### ISSUE TITLE
Dejar de fumar

### ISSUE THREAD

**Issue by gabrielnaone** [carbonecar/telegrambot_test#1]
![image](https://cloud.githubusercontent.com/assets/21368133/18139802/5ab648ac-6f89-11e6-8675-e6c7ba48ac01.png)

![image](https://cloud.githubusercontent.com/assets/21368133/18139880/9fcd17ae-6f89-11e6-8a34-ec78393a7243.png)

**Comment by carbonecar** [comment]
Si. Al finalizar cada consejo de forma aleatoria propone otro consejo. 
Al haber solo 3 consejos, la probabilidad de caer en el mismo es muy alta. 

Entiendo debería de excluir el consejo ya dado la primer vez.  Pero para siempre, no, cierto?

**Comment by carbonecar** [comment]
Vamos a validar bien el flujo.

**Comment by carbonecar** [comment]
Fixed in version V0.8.2
