### ISSUE TITLE
No aparece el teclado

### ISSUE THREAD

**Issue by gabrielnaone** [carbonecar/telegrambot_test#2]
Inicio el bot y cuando me pregunta sexo y edad (todo junto) no aparecen las opciones para reponder.

![image](https://cloud.githubusercontent.com/assets/21368133/18438550/4659584c-78d8-11e6-8711-61045fe5b37e.png)

**Comment by carbonecar** [comment]
Aparecen las dos respuestas juntas porque se ingresaron dos comandos
"/start" y "/start".

Lo que se puede hacer es obligar a que no pase a la pregunta de edad a
menos que ingrese alguna de las opciones que debería de haber mostrado.

Estás de acuerdo?.

**Comment by gabrielnaone** [comment]
Exacto, que vaya paso a paso.

**Comment by carbonecar** [comment]
Fixed en la próxima versión.
